title: RS UNION SENSE
language: pt

copyright: "Copyright (c) 2024 RS UNION SENSE"

author: RS UNION SENSE
keywords: "RS UNION SENSE, RS UNION SENSE, RS UNION SENSE, RS UNION SENSE, RS UNION SENSE"
tagline: "RS UNION SENSE | RS UNION SENSE"
description: "RS UNION SENSE"
url: ""
baseurl: "rs-union-sense"

social: true
#email: "sorrymybadd@protonmail.com"
#github_url: https://example.com/
#gitlab_url: https://example.com/
#discord_url: https://example.com/
#linkedin_url: https://example.com/
#reddit_url: https://example.com/
#instagram_url: https://example.com/
#threads_url: https://example.com/
#x_url: https://example.com/
#telegram_url: https://example.com/

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      image: "/assets/images/avatar2.png"
      seo:
        type: BlogPosting

sitemap: true

seo:
  type: BlogPosting

feed:
  posts_limit: 20

sass:
  style: compressed
  sass_dir: _sass






#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Este site foi criado com fins informativos para documentar o impacto das enchentes na vida das 
  pessoas no Rio Grande do Sul. Diferente da cobertura superficial da mídia tradicional, nosso objetivo é 
  contar a fundo as histórias dos afetados pelas enchentes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: jekyll-theme-tallneck
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
