title: Tallneck test
language: en

copyright: "Copyright (c) 2024 RS UNION SENSE"

author: RS UNION SENSE
keywords: "tallneck, test, jekyll, theme, jekyll-theme-tallneck"
tagline: "Tallneck test | This a tagline"
description: "Preview for the theme Tallneck for Jeckyll."
url: ""
baseurl: "rs-union-sense"

social: true
email: "test@example.com"
github_url: https://example.com/
gitlab_url: https://example.com/
discord_url: https://example.com/
linkedin_url: https://example.com/
reddit_url: https://example.com/
instagram_url: https://example.com/
threads_url: https://example.com/
x_url: https://example.com/
telegram_url: https://example.com/

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      image: "/assets/images/avatar2.png"
      seo:
        type: BlogPosting

sitemap: true

seo:
  type: BlogPosting

feed:
  posts_limit: 20

sass:
  style: compressed
  sass_dir: _sass





#title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: jekyll-theme-tallneck
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
